4:
    4: [bb1, 3, 6]
    5: [bb1, 3, 7]
    6: [bb1, 3, 8]
    7: [bb1, 3, 9]
    8: [bb1, 3, 10]
5:
    4: [bb1, 3, 15]
    5: [bb1, 3, 14]
    6: [bb1, 3, 13]
    7: [bb1, 3, 12]
    8: [bb1, 3, 11]
6:
    4: [bb1, 3, 16]
    5: [bb1, 3, 17]
    6: [bb1, 3, 18]
    7: [bb1, 3, 19]
    8: [bb1, 3, 20]
7:
    4: [bb1, 3, 25]
    5: [bb1, 3, 24]
    6: [bb1, 3, 23]
    7: [bb1, 3, 22]
    8: [bb1, 3, 21]
8:
    4: [bb1, 3, 26]
    5: [bb1, 3, 27]
    6: [bb1, 3, 28]
    7: [bb1, 3, 29]
    8: [bb1, 3, 30]